### PR TITLE
Fixes for compiler warnings found during MBS User Services development

### LINKED ISSUE #6: Date format for FDT @Expires
The Expires attribute for the FDT is currently computed considering the seconds since Epoch, while it should be the seconds since 1 Jan 1900: 

In RFC 3926/rfc6726: 
The value of the data field represents the 32
      most significant bits of a 64 bit Network Time Protocol (NTP) [5]
      time value.  These 32 bits provide an unsigned integer
      representing the time in seconds relative to 0 hours 1 January
      1900.

### PR DESCRIPTION
**Pull request by davidjwbbc**
This fixes several compiler warnings and errors encountered during development of the MBS User Services components.

This pull request fixes:
- Include dependency for libconfig++ in the CMake files.
- Fix compiler warnings about member variables being initialised out of order.
- Fix mis-matched types from some "auto" variables.
- Fix compiler error about fixed length fields following flexible array fields in a struct.
- Add Klaus's fix for epoch on expiration timestamps in the FDT.

### CODE REVIEW

**Comment by rjb1000** [comment]
@dsilhavy: Is it possible to add @kuehnhammer as a reviewer of this pull request?

**Comment by dsilhavy** [comment]
@rjb1000 I can't add him directly, but I will ping him on Slack.

**Comment by dsilhavy** [comment]
This addresses #6

File: include/EncodingSymbol.h [hunk 1]
```diff
@@ -47,9 +47,10 @@ namespace LibFlute {
       EncodingSymbol(uint32_t id, uint32_t source_block_number, char* encoded_data, size_t data_len, FecScheme fec_scheme)
         : _id(id)
         , _source_block_number(source_block_number)
+        , _fec_scheme(fec_scheme)
```
Comment (dsilhavy) [inline include/EncodingSymbol.h:50]: Isn't that initialised out of order now? Like not matching the order of the constructor arguments.

**Review by dsilhavy — APPROVED** [review]
