### PR TITLE
Fix Empty FDT and add session activation/deactivation

### LINKED ISSUE #19: Sending an "empty" FDT Instance violates the FLUTE specification
# Context

The current behaviour of the *rt-libflute* reference implementation of FLUTE periodically sends an "empty" FDT Instance when there are no objects transmitted in the FLUTE session:

```xml
<FDTInstance ...></FDTInstance>
``` 

Some FLUTE receiver implementations may be relying on this behaviour as a "keep-alive" for the FLUTE session.

# Description of bug

According to [section 3.2 of RFC 3926](https://www.rfc-editor.org/rfc/rfc3926.html#section-3.2):

> Within the file delivery session the FDT is delivered as FDT Instances. An FDT Instance contains **one or more** file description entries of the FDT. Any FDT Instance can be equal to, a subset of, a superset of, or complement any other FDT Instance. A certain FDT Instance may be repeated several times during a session, even after subsequent FDT Instances (with higher FDT Instance ID numbers) have been transmitted. **Each FDT Instance contains at least a single file description entry** and at most the complete FDT of the file delivery session.

This means that the current practice of signalling an "empty" FDT Instance when there are no objects being transmitted is incorrect. No packets should be sent in this case, and it should not be used to signal "keep-alive" for the FLUTE session.

### LINKED ISSUE #47: Implement life-cycle model for FLUTE sessions
When the rt-libflute library is used by the MBSTF (as specified in 3GPP TS 26.502 and TS 29.581), the MBS Distribution Session may switch between an inactive and active state based on explicit configuration (e.g. timers) or as a consequence of certain failure scenarios.

To support this, we would like to be able to temporarily suspend a FLUTE session without destroying its internal state such that it can be reactivated at a later point with the same TSI and knowledge of previous TOI usage in that session.

As well as being able to (de)(re)activate an existing FLUTE session, we would also like to be able to create a FLUTE session in an initially inactive state. In this state, objects can be added to the session by the library invoker, but no packets are actually transmitted until the FLUTE session is activated.

### PR DESCRIPTION
**Pull request by davidjwbbc**
This PR stops empty FDTs from being transmitted and adds `Transmitter` object methods to activate or deactivate the transmission of the FLUTE session.

## FDT improvements

The FDT is no longer transmitted in the FLUTE session if it doesn't contain at least one item. This complies with [RFC 3926 section 3.2](https://www.rfc-editor.org/rfc/rfc3926.html#section-3.2):
> An FDT Instance contains one or more file description entries of the FDT.

As a result, an empty FDT is never transmitted.

The incrementing of the FDT instance ID has also been improved to reduce the number of increments. The value is now incremented by only 1 between transmitted instances of the FDT, even when multiple changes are made to the FDT between transmissions.

## Activity lifecycle

The `Transmitter` object can now be in an **active** or **inactive** state, allowing the FLUTE session to be paused and resumed.

- In the active state, packets are transmitted for the FDT and file transmission objects.
- In the inactive state, no packets are transmitted. In this state, the list of files to transmit can still be modified, and the resulting packets are sent once the `Transmitter` object becomes active.

The following methods are used in conjunction with this:
- The `Transmitter` constructor method can now take an optional indicator to determine if instances should start in the active or inactive state.
- An `activate()` method is introduced to activate the `Transmitter` if it is currently in the inactive state.
- A `deactivate()` method is introduced to change the `Transmitter` object to the inactive state if it is currently active.
- A `number_of_files()` method is added to interrogate the `Transmitter` object for how many files it has left to transmit. This allows applications to monitor the `Transmitter` object in order to drain the *File* transmissions before calling `deactivate()`.

## Issues fixed by this PR

Closes #19
Closes #47

### CODE REVIEW

**Review by rjb1000 — DISMISSED** [review]
Thanks, @davidjwbbc.

**Comment by jordijoangimenez** [comment]
Many thanks, @davidjwbbc.

**Review by jordijoangimenez — DISMISSED** [review]

File: include/Transmitter.h [hunk 1]
```diff
@@ -560,10 +565,36 @@ namespace LibFlute {
...
+      * been completely transmitted.
+      */
+      void deactivate();
+
+     /**
+      * Get number of files currently being sent
+      *
+      * @return The number of files in the queue for sending.
+      */
+      size_t number_of_files() { std::lock_guard<std::mutex> guard(_files_mutex); return _files.size(); };
```
Comment (dsilhavy) [inline include/Transmitter.h:592]: Suggest to refine the description and specifically say `Get number of files currently in the queue for sending` (similar to the description of `return`)

File: include/Transmitter.h [hunk 2]
```diff
@@ -560,10 +565,36 @@ namespace LibFlute {
...
+      * Sending of packets will start or resume until the deactivate() method is called or this Transmitter is destroyed.
+      */
+      void activate();
+
+     /**
+      * Deactivate the FLUTE session
+      *
+      * If the Transmitter is currently active then the FLUTE stream is halted and the state is changed to deactivated. Sending of
+      * packets will be halted until the activate() method is called. Note that this will pause File transmission part way through
+      * if a File is currently being transmitted. If the application wishes for deactivation once Files have finished sending then
```
Comment (dsilhavy) [inline include/Transmitter.h:581]: I think a nice addition would be to add a flag to the `deactivate` method to trigger the deactivation once all files are finished sending. Something like `deactivate(finishOngoingFileTransmissions=false)` . Instead of leaving this up to the user/application. 

I can add an issue for this enhancement.

File: src/AlcPacket.cpp [hunk 3]
```diff
@@ -211,7 +211,7 @@ LibFlute::AlcPacket::AlcPacket(uint16_t tsi, uint16_t toi, LibFlute::FecOti fec_
     *((uint16_t*)hdr_ptr) = htons(_fec_oti.encoding_symbol_length);
     hdr_ptr += 2;
     *((uint32_t*)hdr_ptr) = htonl(_fec_oti.max_source_block_length);
-    hdr_ptr += 4;
+    //hdr_ptr += 4;
```
Comment (dsilhavy) [inline src/AlcPacket.cpp]: Suggest to remove instead of commenting

File: src/Transmitter.cpp [hunk 4]
```diff
@@ -499,10 +500,11 @@ Transmitter::Transmitter ( const std::string& address, short port,
     .max_source_block_length = max_source_block_length};
   _fdt = std::make_unique<FileDeliveryTable>(1, _fec_oti, fdt_namespace);
 
-  _fdt_timer.expires_from_now(boost::posix_time::seconds(_fdt_repeat_interval));
-  _fdt_timer.async_wait( boost::bind(&Transmitter::fdt_send_tick, this));
-
-  send_next_packet();
+  if (_active) {
+    _fdt_timer.expires_from_now(boost::posix_time::seconds(_fdt_repeat_interval));
```
Comment (dsilhavy) [inline src/Transmitter.cpp]: Suggest to put these two function calls into a dedicated function instead of repeating it multiple times

File: src/Transmitter.cpp [hunk 5]
```diff
@@ -684,74 +703,101 @@ auto Transmitter::send_next_packet() -> void
...
+        _send_timer.async_wait( boost::bind(&Transmitter::send_next_packet, this));
+      }
     }
   }
 }
 
+auto Transmitter::activate() -> void
+{
+  if (!_active) {
+    _active = true;
```
Comment (dsilhavy) [inline src/Transmitter.cpp:783]: Do we need to activate the `send_timer` here again?

**Review by dsilhavy — DISMISSED** [review]
Thanks @davidjwbbc I added some minor comments/questions. No blocker from my side so I approve the PR despite the comments not being addressed yet

File: include/Transmitter.h (hunk 2 above)
Comment (dsilhavy) [reply include/Transmitter.h:581]: Added an issue for this: https://github.com/5G-MAG/rt-libflute/issues/50

File: src/Transmitter.cpp (hunk 5 above)
Comment (davidjwbbc) [reply src/Transmitter.cpp:783]: That gets reactivated by the call to `send_next_packet()`.

File: src/AlcPacket.cpp (hunk 3 above)
Comment (davidjwbbc) [reply src/AlcPacket.cpp]: done

File: src/Transmitter.cpp (hunk 4 above)
Comment (davidjwbbc) [reply src/Transmitter.cpp]: Done

File: include/Transmitter.h (hunk 2 above)
Comment (davidjwbbc) [reply include/Transmitter.h:581]: Will leave this as a backlog item for now

File: include/Transmitter.h (hunk 1 above)
Comment (davidjwbbc) [reply include/Transmitter.h:592]: Done

**Comment by dsilhavy** [comment]
Thanks for the additional changes @davidjwbbc

**Review by dsilhavy — APPROVED** [review]
